# Generated by Django 5.2.6 on 2025-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="содержимое"),
        ),
    ]
