# Generated by Django 5.2.6 on 2025-10-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_note_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["created_at"],
                "verbose_name": "заметка блога",
                "verbose_name_plural": "заметки блога",
            },
        ),
    ]
