# Generated by Django 5.2.6 on 2025-09-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=100, verbose_name="наименование")),
                ("category_description", models.CharField(max_length=100, verbose_name="описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=100, verbose_name="наименование")),
                ("product_description", models.CharField(max_length=100, verbose_name="описание")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="изображение")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="цена за покупку"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["product_name"],
            },
        ),
    ]
