# Generated by Django 4.2.2 on 2025-10-26 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=100, verbose_name="наименование")),
                ("category_description", models.CharField(max_length=100, verbose_name="описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("inn", models.CharField(max_length=20, unique=True, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="телефон")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
            ],
            options={
                "verbose_name": "контактная информация",
                "verbose_name_plural": "контактные данные",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=100, verbose_name="наименование")),
                ("product_description", models.CharField(max_length=100, verbose_name="описание")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="изображение")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="цена за покупку"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("is_active", models.BooleanField(default=False, verbose_name="Опубликовать")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["product_name"],
                "permissions": [("can_unpublish_product", "can unpublish product")],
            },
        ),
    ]
