# Generated by Django 5.2.6 on 2025-09-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                ("inn", models.CharField(max_length=20, unique=True, verbose_name="ИНН")),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="телефон")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
            ],
            options={
                "verbose_name": "контактная информация",
                "verbose_name_plural": "контактные данные",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
    ]
