# Generated by Django 5.2.6 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactinfo_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активный"),
        ),
    ]
