# Generated by Django 4.2.2 on 2025-10-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
